version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: covid_postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_DB: covid_db
      POSTGRES_USER: covid_user
      POSTGRES_PASSWORD: covid_2025
    volumes:
      - covid_pgdata:/var/lib/postgresql/data
      - ./data/processed:/app/data/processed
    networks:
      - covid_net

volumes:
  covid_pgdata:

networks:
  covid_net:
